;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		c-electric-brace
		c-electric-delete-forward
		c-electric-paren
		c-electric-slash
		c-electric-star
		c-electric-semi&comma
		dired-toggle-read-only
		kill-region
		yas-expand
		))

(setq mc/cmds-to-run-once
      '(
		beginning-of-buffer
		dired-do-touch
		ido-find-file
		))
