;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		Buffer-menu-delete
		c-electric-brace
		c-electric-colon
		c-electric-delete-forward
		c-electric-paren
		c-electric-semi&comma
		c-electric-slash
		c-electric-star
		dired-toggle-read-only
		goto-line
		indent-for-tab-command
		kill-region
		org-kill-line
		yas-expand
		))

(setq mc/cmds-to-run-once
      '(
		beginning-of-buffer
		dired-do-touch
		ido-find-file
		ido-switch-buffer
		ido-write-file
		multiple-cursors-mode
		))
