;; (custom-set-faces ; only one 'custom-set-faces' entry must exist in custom.el
;;  '(default ((t (:foreground "white" :background "black"
;;  :size "10" :family "monospace"
;; ))) t)
;;  '(cperl-array-face ((t (:foreground "orangered" :bold t))))
;;  '(cperl-hash-face ((t (:foreground "Red" :bold t))))
;;  '(cperl-nonoverridable-face ((t (:foreground "orange" :bold t))))
;;  '(custom-button-face ((t (:bold t :foreground "#3fdfcf"))))
;;  '(custom-group-tag-face ((t (:underline t :foreground "blue"))))
;;  '(custom-saved-face ((t (:underline t :foreground "orange"))))
;;  '(custom-state-face ((t (:foreground "green3"))))
;;  '(custom-variable-button-face ((t (:bold t :underline t :foreground "white"))))
;;  '(dired-face-permissions ((t (:foreground "green"))))
;;  '(font-latex-bold-face ((((class color) (background light)) (:bold t))))
;;  '(font-latex-italic-face ((((class color) (background light)) (:italic t))))
;;  '(font-latex-math-face ((((class color) (background light)) (:foreground "green3"))))
;;  '(font-latex-sedate-face ((((class color) (background light)) (:foreground "#ffc14d"))))
;;  '(font-lock-comment-face ((t (:foreground "#bd48aa"))))
;;  '(font-lock-doc-string-face ((t (:foreground "Wheat3"))))
;;  '(font-lock-function-name-face ((t (:foreground "white" :bold t))))
;;  '(font-lock-keyword-face ((t (:foreground "#ffc14d" :bold))))
;;  '(font-lock-brace-face ((t (:foreground "blue" :bold))))
;;  '(font-lock-preprocessor-face ((t (:foreground "red" :bold t))))
;;  '(font-lock-reference-face ((t (:foreground "orangered"))))
;;  '(font-lock-string-face ((t (:foreground "#99ff00"))))
;;  '(font-lock-type-face ((t (:foreground "#886fff" :bold t))))
;;  '(font-lock-variable-name-face ((t (:foreground "white" :bold t))))
;;  '(font-lock-warning-face ((t (:foreground "Violetred"  :bold t))))
;;  '(highlight ((t (:foreground "red3" :background "white"))) t)
;;  '(isearch ((t (:foreground "red" :background "white"))) t)
;;  '(list-mode-item-selected ((t (:foreground "green"))) t)
;;  '(message-cited-text ((t (:bold t :italic nil))))
;;  '(secondary-selection ((t (:foreground "white" :background "red"))) t)
;;  '(text-cursor ((t (:foreground "black" :background "green"))) t)
;;  '(zmacs-region ((t (:background "RoyalBlue"))) t)
;;  )


(custom-set-faces ; only one 'custom-set-faces' entry must exist in custom.el
 '(default ((t (:foreground "white" :background "black"
; :size "13" ;:family "monospace"
))) t)
 '(cperl-array-face ((t (:foreground "orangered" :bold t))))
 '(cperl-hash-face ((t (:foreground "Red" :bold t))))
 '(cperl-nonoverridable-face ((t (:foreground "orange" :bold t))))
 '(custom-button-face ((t (:bold t :foreground "#3fdfcf"))))
 '(custom-group-tag-face ((t (:underline t :foreground "blue"))))
 '(custom-saved-face ((t (:underline t :foreground "orange"))))
 '(custom-state-face ((t (:foreground "green3"))))
 '(custom-variable-button-face ((t (:bold t :underline t :foreground "white"))))
 '(dired-face-permissions ((t (:foreground "green"))))
 '(font-latex-bold-face ((((class color) (background light)) (:bold t))))
 '(font-latex-italic-face ((((class color) (background light)) (:italic t))))
 '(font-latex-math-face ((((class color) (background light)) (:foreground "green3"))))
 '(font-latex-sedate-face ((((class color) (background light)) (:foreground "gold"))))
 '(font-lock-comment-face ((t (:foreground "orange3"))))
 '(font-lock-doc-string-face ((t (:foreground "Wheat3"))))
 '(font-lock-function-name-face ((t (:foreground "orange" :bold t))))
 '(font-lock-keyword-face ((t (:foreground "gold"))))
 '(font-lock-preprocessor-face ((t (:foreground "red" :bold t))))
 '(font-lock-reference-face ((t (:foreground "orangered"))))
 '(font-lock-string-face ((t (:foreground "green3"))))
 '(font-lock-type-face ((t (:foreground "#886fff" :bold t))))
 '(font-lock-variable-name-face ((t (:foreground "yellow" :bold t))))
 '(font-lock-warning-face ((t (:foreground "Violetred"  :bold t))))
 '(highlight ((t (:foreground "red3" :background "white"))) t)
 '(isearch ((t (:foreground "red" :background "white"))) t)
 '(list-mode-item-selected ((t (:foreground "green"))) t)
 '(message-cited-text ((t (:bold t :italic nil))))
 '(secondary-selection ((t (:foreground "white" :background "red"))) t)
 '(text-cursor ((t (:foreground "black" :background "green"))) t)
 '(zmacs-region ((t (:background "RoyalBlue"))) t)
 )
